#!/usr/bin/env python3
"""Walk TOS for attribute codes on GPS-quartet devices.

Output: ``data/attribute_codes.yaml`` — one entry per distinct attribute
code seen, with subtype(s) it appears on, sample values, period count,
and an empty ``classification`` field for operator review.

Used to bootstrap the inherent / mutable taxonomy required by
``tos audit attribute-dates``. See ``.interrogate-tos-attribute-dates-audit.md``.

Usage::

    python scripts/harvest_attribute_codes.py
    python scripts/harvest_attribute_codes.py --stations ARHO RHOF VMEY ...

Reads live TOS — no cassette infrastructure for the harvest path yet.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from tostools.api.tos_client import TOSClient  # noqa: E402
from tostools.gps_metadata_qc import URL_REST_TOS  # noqa: E402

GPS_QUARTET = ("gnss_receiver", "antenna", "radome", "monument")

# Mix of "clean" and "messy" stations — diverse equipment generations, varying
# data hygiene, spanning Iceland geographically. ARHO is the worked example
# from the destination doc.
DEFAULT_STATIONS = [
    "ARHO",
    "RHOF",
    "VMEY",
    "AKUR",
    "REYK",
    "HOFN",
    "AUST",
    "DYNC",
    "SJUK",
    "GRVA",
]


def harvest_station(
    client: TOSClient, marker: str, agg: Dict[str, Dict[str, Any]]
) -> None:
    """Pull station history → device histories → attribute codes into agg."""
    hits = client.search_stations(marker, domains="geophysical")
    if not hits:
        print(f"  [skip] {marker}: not found in TOS", file=sys.stderr)
        return
    station_id = hits[0]["id_entity"]
    history = client.get_entity_history(station_id)
    if not history:
        print(f"  [skip] {marker}: no history", file=sys.stderr)
        return
    children = history.get("children_connections") or []
    seen_device_ids = set()
    for conn in children:
        child_id = conn.get("id_entity_child")
        if child_id is None or child_id in seen_device_ids:
            continue
        seen_device_ids.add(child_id)
        try:
            dev_history = client.get_entity_history(int(child_id))
        except Exception as exc:  # noqa: BLE001
            print(f"  [warn] device {child_id}: {exc}", file=sys.stderr)
            continue
        if not dev_history:
            continue
        subtype = dev_history.get("code_entity_subtype")
        if subtype not in GPS_QUARTET:
            continue
        for attr in dev_history.get("attributes") or []:
            code = attr.get("code")
            if not code:
                continue
            entry = agg.setdefault(
                code,
                {
                    "subtypes": set(),
                    "sample_values": [],
                    "n_periods": 0,
                    "n_devices": 0,
                    "_device_ids": set(),
                },
            )
            entry["subtypes"].add(subtype)
            entry["n_periods"] += 1
            if int(child_id) not in entry["_device_ids"]:
                entry["_device_ids"].add(int(child_id))
                entry["n_devices"] += 1
            val = attr.get("value")
            if val is not None and len(entry["sample_values"]) < 3:
                str_val = str(val)
                if str_val not in entry["sample_values"]:
                    entry["sample_values"].append(str_val)
    print(
        f"  [ok] {marker}: {len(seen_device_ids)} devices walked",
        file=sys.stderr,
    )


def render_yaml(agg: Dict[str, Dict[str, Any]]) -> str:
    """Emit the catalog file. Avoid PyYAML dependency — hand-format for control."""
    lines = [
        "# TOS attribute codes catalog for GPS-quartet devices",
        "# Auto-generated by scripts/harvest_attribute_codes.py; classify each",
        "# code as 'inherent' (property of the physical device, doesn't change"
        " — e.g. serial_number, model)",
        "# or 'mutable' (can legitimately transition mid-life — e.g."
        " firmware_version, status).",
        "#",
        "# Replace each 'classification: TODO' with 'inherent' or 'mutable'.",
        "# Add a 'why' line where the reasoning isn't obvious.",
        "",
    ]
    for code in sorted(agg):
        e = agg[code]
        subtypes = sorted(e["subtypes"])
        sample = e["sample_values"]
        lines.append(f"{code}:")
        lines.append(f"  classification: TODO  # inherent | mutable")
        lines.append(f"  subtypes: [{', '.join(subtypes)}]")
        lines.append(
            f"  n_devices: {e['n_devices']}  # how many devices in the sample"
        )
        lines.append(
            f"  n_periods: {e['n_periods']}  # total periods seen in the sample"
        )
        if sample:
            quoted = ", ".join(f'"{s}"' for s in sample)
            lines.append(f"  sample_values: [{quoted}]")
        else:
            lines.append("  sample_values: []  # all values were null in sample")
        lines.append("  why: \"\"")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--stations",
        nargs="+",
        default=DEFAULT_STATIONS,
        help=f"Station markers to walk (default: {' '.join(DEFAULT_STATIONS)})",
    )
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "data" / "attribute_codes.yaml"),
        help="Path for the draft YAML",
    )
    args = parser.parse_args()

    client = TOSClient(base_url=URL_REST_TOS)
    agg: Dict[str, Dict[str, Any]] = {}

    print(
        f"Walking {len(args.stations)} stations for GPS-quartet attribute codes...",
        file=sys.stderr,
    )
    for marker in args.stations:
        harvest_station(client, marker, agg)

    yaml = render_yaml(agg)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml, encoding="utf-8")

    print(
        f"\nWrote {out_path} — {len(agg)} distinct codes across the sample.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
